# EMTA andmete analüüs

##### faili nimi . ipynb e interactive python notebook

## Ettevalmistus

In [ ]:
import pandas as pd #csv faili lugemiseks nt
import duckdb #sql kasutamiseks
import matplotlib as plt # tabelite tegemiseks
import seaborn as sns # tabelite tegemiseks

## Andmetega tutvumine

In [13]:
data_raw_this_year = pd.read_csv("tasutud_maksud_kaesolev_aasta.csv", nrows=5)
data_raw_this_year 

# mida üks rida tähendab? 
# nrows - mitu rida näed tabelist, tabel algab alati 0
# andmeid saab sisse lugeda nii panda kui duckdb

,Andmete seis,Registrikood,Nimi,Liik,Maakond,Tegevusala,Aasta,Riiklikud maksud I kv,Riiklikud maksud II kv,Riiklikud maksud III kv,...,Tööjõumaksud III kv,Tööjõumaksud IV kv,Käive I kv,Käive II kv,Käive III kv,Käive IV kv,Töötajate arv I kv,Töötajate arv II kv,Töötajate arv III kv,Töötajate arv IV kv
0,10.04.2026,10000018,AMSERV AUTO OSAÜHING,Äriühing,Harju ( Tallinn ),HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOO...,2025,1723565,2038192.0,2141341.0,...,1213643.0,1131417.0,34309154,30413704.0,23282177.0,21724706.0,254.0,243.0,244.0,240.0
1,10.04.2026,10000018,AMSERV AUTO OSAÜHING,Äriühing,Harju ( Tallinn ),HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOO...,2026,1561762,NaN,NaN,...,NaN,NaN,19993085,NaN,NaN,NaN,236.0,NaN,NaN,NaN
2,10.04.2026,10000024,"EESTI RAAMAT, OÜ",Äriühing,Harju ( Tallinn ),INFO JA SIDE,2025,40888,41980.0,38723.0,...,38979.0,36127.0,236677,235518.0,206299.0,280010.0,11.0,11.0,10.0,10.0
3,10.04.2026,10000024,"EESTI RAAMAT, OÜ",Äriühing,Harju ( Tallinn ),INFO JA SIDE,2026,48644,NaN,NaN,...,NaN,NaN,299247,NaN,NaN,NaN,11.0,NaN,NaN,NaN
4,10.04.2026,10000062,ALDO KOPPEL,FIE,Ida-Viru ( Lüganuse vald ),"PÕLLUMAJANDUS, METSAMAJANDUS JA KALAPÜÜK",2025,313,342.0,635.0,...,0.0,NaN,1941,2925.0,9273.0,906.0,NaN,NaN,NaN,NaN

In [18]:
duckdb.sql(""" 
    FROM 'tasutud_maksud_varasemad_aastad.csv' 
    LIMIT 5 
""").df() 

# df e tabeli kujul

,Andmete seis,Registrikood,Nimi,Liik,Maakond,Tegevusala,Aasta,Riiklikud maksud I kv,Riiklikud maksud II kv,Riiklikud maksud III kv,...,Tööjõumaksud III kv,Tööjõumaksud IV kv,Käive I kv,Käive II kv,Käive III kv,Käive IV kv,Töötajate arv I kv,Töötajate arv II kv,Töötajate arv III kv,Töötajate arv IV kv
0,2026-04-10,01834351,"LOMBI-13, GARAAŽIKOOPERATIIV",Äriühing,Harju ( Tallinn ),NaN,2022,<NA>,288,<NA>,...,<NA>,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2026-04-10,01834351,"LOMBI-13, GARAAŽIKOOPERATIIV",Äriühing,Harju ( Tallinn ),NaN,2023,<NA>,288,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2026-04-10,01834351,"LOMBI-13, GARAAŽIKOOPERATIIV",Äriühing,Harju ( Tallinn ),NaN,2024,288,52,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2026-04-10,01834575,"KUNDERI 24, GARAAŽIKOOPERATIIV",Äriühing,Harju ( Tallinn ),NaN,2024,<NA>,<NA>,268,...,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2026-04-10,10000018,AMSERV AUTO OSAÜHING,Äriühing,Harju ( Tallinn ),HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOO...,2022,1300554,1645555,1185273,...,923188,950362,22930261,31976194,26140614,31599227,214,228,231,232

In [22]:
data_raw_new = pd.read_csv("tasutud_maksud_kaesolev_aasta.csv", nrows=5)
data_raw_old = pd.read_csv("tasutud_maksud_varasemad_aastad.csv", nrows=5)

data_raw_new.columns == data_raw_old.columns

# kontrollime, kas mõlema tabeli tulbad kattuvad
# == kas võrdub? vs = võrdub

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [26]:
data_raw = duckdb.sql(""" 
    FROM 'tasutud_maksud_kaesolev_aasta.csv'
    UNION ALL
    FROM 'tasutud_maksud_varasemad_aastad.csv'
    LIMIT 5 
""")

data_raw 

# joine saab kasutada ainult juhul, kui kõik tulbad kattuvad mõlemas tabelis
# union - kustutab ära duplikaadid
# union all jätab kõik tulbad mõlemas tabelis alles, ka siis, kui ei kattu

┌──────────────┬──────────────┬──────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────────────────┬───────┬───────────────────────┬────────────────────────┬─────────────────────────┬────────────────────────┬───────────────────┬────────────────────┬─────────────────────┬────────────────────┬────────────┬─────────────┬──────────────┬─────────────┬────────────────────┬─────────────────────┬──────────────────────┬─────────────────────┐
│ Andmete seis │ Registrikood │         Nimi         │   Liik   │          Maakond           │                           Tegevusala                            │ Aasta │ Riiklikud maksud I kv │ Riiklikud maksud II kv │ Riiklikud maksud III kv │ Riiklikud maksud IV kv │ Tööjõumaksud I kv │ Tööjõumaksud II kv │ Tööjõumaksud III kv │ Tööjõumaksud IV kv │ Käive I kv │ Käive II kv │ Käive III kv │ Käive IV kv │ Töötajate arv I kv │ Töötajate arv II kv │ Töötajate arv III kv │ Töötajate arv IV kv │
│     date     │   varchar    │       varchar        │ varchar  │          varchar           │                             varchar                             │ int64 │         int64         │         int64          │          int64          │         int64          │       int64       │       int64        │        int64        │       int64        │   int64    │    int64    │    int64     │    int64    │       int64        │        int64        │        int64         │        int64        │
├──────────────┼──────────────┼──────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────────────────┼───────┼───────────────────────┼────────────────────────┼─────────────────────────┼────────────────────────┼───────────────────┼────────────────────┼─────────────────────┼────────────────────┼────────────┼─────────────┼──────────────┼─────────────┼────────────────────┼─────────────────────┼──────────────────────┼─────────────────────┤
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn )          │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2025 │               1723565 │                2038192 │                 2141341 │                1844403 │           1259900 │            1229742 │             1213643 │            1131417 │   34309154 │    30413704 │     23282177 │    21724706 │                254 │                 243 │                  244 │                 240 │
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn )          │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2026 │               1561762 │                   NULL │                    NULL │                   NULL │           1088007 │               NULL │                NULL │               NULL │   19993085 │        NULL │         NULL │        NULL │                236 │                NULL │                 NULL │                NULL │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn )          │ INFO JA SIDE                                                    │  2025 │                 40888 │                  41980 │                   38723 │                  45274 │             37574 │              38125 │               38979 │              36127 │     236677 │      235518 │       206299 │      280010 │                 11 │                  11 │                   10 │                  10 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn )          │ INFO JA SIDE                                                    │  2026 │                 48644 │                   NULL │                    NULL │                   NULL │             40000 │               NULL │                NULL │               NULL │     299247 │        NULL │         NULL │        NULL │                 11 │                NULL │                 NULL │                NULL │
│ 2026-04-10   │ 10000062     │ ALDO KOPPEL          │ FIE      │ Ida-Viru ( Lüganuse vald ) │ PÕLLUMAJANDUS, METSAMAJANDUS JA KALAPÜÜK                        │  2025 │                   313 │                    342 │                     635 │                   NULL │                 0 │                  0 │                   0 │               NULL │       1941 │        2925 │         9273 │         906 │               NULL │                NULL │                 NULL │                NULL │
└──────────────┴──────────────┴──────────────────────┴──────────┴────────────────────────────┴─────────────────────────────────────────────────────────────────┴───────┴───────────────────────┴────────────────────────┴─────────────────────────┴────────────────────────┴───────────────────┴────────────────────┴─────────────────────┴────────────────────┴────────────┴─────────────┴──────────────┴─────────────┴────────────────────┴─────────────────────┴──────────────────────┴─────────────────────┘

In [32]:
# andmete vaatlemine 
# kontrolli tulpade andmetüüpe
# eemalda ebavajalik - date tabel?
# lahuta andmeid, kui vaja - tee maakond kaheks, et saada nt harjumaa ja tallinn eraldi
# tõmba andmeid kokku, kui võimalik - kvartalid võiksid olla eraldi ridadel, mitte eraldi tulpades (iga tulp kirjeldab erinevaid andmeid)
# kvartali tulba nimi võiks olla mugavam

In [31]:
data_unpivot = duckdb.sql("""
WITH base AS (
    SELECT
        "Andmete seis",
        "Registrikood",
        "Nimi",
        "Liik",
        "Maakond",
        "Tegevusala",
        "Aasta",
        "Riiklikud maksud I kv" AS riiklikud_maksud_1,
        "Riiklikud maksud II kv" AS riiklikud_maksud_2,
        "Riiklikud maksud III kv" AS riiklikud_maksud_3,
        "Riiklikud maksud IV kv" AS riiklikud_maksud_4,
        "Tööjõumaksud I kv" AS toojou_maksud_1,
        "Tööjõumaksud II kv" AS toojou_maksud_2,
        "Tööjõumaksud III kv" AS toojou_maksud_3,
        "Tööjõumaksud IV kv" AS toojou_maksud_4,
        "Käive I kv" AS kaive_1,
        "Käive II kv" AS kaive_2,
        "Käive III kv" AS kaive_3,
        "Käive IV kv" AS kaive_4,
        "Töötajate arv I kv" AS tootajad_1,
        "Töötajate arv II kv" AS tootajad_2,
        "Töötajate arv III kv" AS tootajad_3,
        "Töötajate arv IV kv" AS tootajad_4
    FROM data_raw
)
UNPIVOT base
ON
    (riiklikud_maksud_1, toojou_maksud_1, kaive_1, tootajad_1),
    (riiklikud_maksud_2, toojou_maksud_2, kaive_2, tootajad_2),
    (riiklikud_maksud_3, toojou_maksud_3, kaive_3, tootajad_3),
    (riiklikud_maksud_4, toojou_maksud_4, kaive_4, tootajad_4)
INTO
    NAME kvartal
    VALUE riiklikud_maksud, toojoumaksud, kaive, tootajate_arv;
""")

data_unpivot 

# jutumärgid on olulised, kui sõnadel on tühik sees, alakriipsu kasutades sõnade vahel ei pea jutumärke kasutama 
# lisasime tabeli importi (duckdb ja sql) juurde nime data_raw, et pikka importi ei peaks uues valemis kasutama

┌──────────────┬──────────────┬──────────────────────┬──────────┬───────────────────┬─────────────────────────────────────────────────────────────────┬───────┬───────────────────────────────────────────────────────┬──────────────────┬──────────────┬──────────┬───────────────┐
│ Andmete seis │ Registrikood │         Nimi         │   Liik   │      Maakond      │                           Tegevusala                            │ Aasta │                        kvartal                        │ riiklikud_maksud │ toojoumaksud │  kaive   │ tootajate_arv │
│     date     │   varchar    │       varchar        │ varchar  │      varchar      │                             varchar                             │ int64 │                        varchar                        │      int64       │    int64     │  int64   │     int64     │
├──────────────┼──────────────┼──────────────────────┼──────────┼───────────────────┼─────────────────────────────────────────────────────────────────┼───────┼───────────────────────────────────────────────────────┼──────────────────┼──────────────┼──────────┼───────────────┤
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn ) │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2025 │ riiklikud_maksud_1_toojou_maksud_1_kaive_1_tootajad_1 │          1723565 │      1259900 │ 34309154 │           254 │
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn ) │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2025 │ riiklikud_maksud_2_toojou_maksud_2_kaive_2_tootajad_2 │          2038192 │      1229742 │ 30413704 │           243 │
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn ) │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2025 │ riiklikud_maksud_3_toojou_maksud_3_kaive_3_tootajad_3 │          2141341 │      1213643 │ 23282177 │           244 │
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn ) │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2025 │ riiklikud_maksud_4_toojou_maksud_4_kaive_4_tootajad_4 │          1844403 │      1131417 │ 21724706 │           240 │
│ 2026-04-10   │ 10000018     │ AMSERV AUTO OSAÜHING │ Äriühing │ Harju ( Tallinn ) │ HULGI- JA JAEKAUBANDUS; MOOTORSÕIDUKITE JA MOOTORRATASTE REMONT │  2026 │ riiklikud_maksud_1_toojou_maksud_1_kaive_1_tootajad_1 │          1561762 │      1088007 │ 19993085 │           236 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn ) │ INFO JA SIDE                                                    │  2025 │ riiklikud_maksud_1_toojou_maksud_1_kaive_1_tootajad_1 │            40888 │        37574 │   236677 │            11 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn ) │ INFO JA SIDE                                                    │  2025 │ riiklikud_maksud_2_toojou_maksud_2_kaive_2_tootajad_2 │            41980 │        38125 │   235518 │            11 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn ) │ INFO JA SIDE                                                    │  2025 │ riiklikud_maksud_3_toojou_maksud_3_kaive_3_tootajad_3 │            38723 │        38979 │   206299 │            10 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn ) │ INFO JA SIDE                                                    │  2025 │ riiklikud_maksud_4_toojou_maksud_4_kaive_4_tootajad_4 │            45274 │        36127 │   280010 │            10 │
│ 2026-04-10   │ 10000024     │ EESTI RAAMAT, OÜ     │ Äriühing │ Harju ( Tallinn ) │ INFO JA SIDE                                                    │  2026 │ riiklikud_maksud_1_toojou_maksud_1_kaive_1_tootajad_1 │            48644 │        40000 │   299247 │            11 │
└──────────────┴──────────────┴──────────────────────┴──────────┴───────────────────┴─────────────────────────────────────────────────────────────────┴───────┴───────────────────────────────────────────────────────┴──────────────────┴──────────────┴──────────┴───────────────┘
  10 rows                                                                                                                                                                                                                                                               12 columns

In [42]:
def eralda_maakond(maakond: str) -> str: 
    return maakond.split(" ( ") [0] 


def eralda_kov(maakond: str) -> str: 
    return maakond.split(" ( ") [1] [:-2]

duckdb.create_function("eralda_maakond", eralda_maakond)
duckdb.create_function("eralda_kov", eralda_kov)

# pean mitte ainult defineerima, vaid ka looma funktsiooni 'eraldi_maakond/kov', et seda hiljem edasi kasutada

# eraldame maakonna tulbas maakonna ja kov / linna, maakond on element nr 0, kov/linn on element nr 2 (sest esimene sulg on element 1)
# kuna eelnev tingimus ei sobi meie kov/linn, lisasime spliti tingimuse, et teine sisu/element algab peale: tühik+sulg+tühik
# :-2 ehk võta kogu sisu, välja arvatud kaks viimast elementi, milleks antud juhul on: tühik + )

NotImplementedException: Not implemented Error: A function by the name of 'eralda_maakond' is already created, creating multiple functions with the same name is not supported yet, please remove it first